name: qiime2-amplicon-2024.2
channels:
  - bioconda
  - conda-forge
  - https://packages.qiime2.org/qiime2/2024.2/amplicon/released
  - defaults
dependencies:
  # QIIME2 Essentials
  - qiime2=2024.2
  - q2cli=2024.2
  - q2-demux=2024.2
  - q2-feature-table=2024.2
  - q2-taxa=2024.2
  - q2-deblur=2024.2
  - q2-quality-control=2024.2
  - q2-quality-filter=2024.2
  - q2-diversity=2024.2

  # PICRUSt2
  - picrust2=2.5.2

  # Bioinformatics tools
  - vsearch=2.22.1
  - cutadapt=4.6
  - fastqc
  - biom-format=2.1.14

  # Python
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - click
  - biopython
  - scipy

  # Utilities
  - wget
  - curl