name: qiime2-amplicon-2024.10
channels:
  - https://packages.qiime2.org/qiime2/2024.10/amplicon/released
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # QIIME2 Amplicon Distribution
  - qiime2-amplicon

  # Herramientas adicionales para análisis de microbioma
  - picrust2
  - sra-tools

  # Python y paquetes base
  - python=3.10
  - pip